const { v4: uuid } = require("uuid");
const { save } = require("./db");

const demoArtisanId = "artisan-demo-001";
const demoArtisan2Id = "artisan-demo-002";
const demoBuyerId = "buyer-demo-001";

// Spread createdAt dates across recent months so the admin growth
// chart and "recent" lists have a realistic shape.
const daysAgo = (d, h = 0) => new Date(Date.now() - (d * 24 + h) * 60 * 60 * 1000).toISOString();
const img = (id) => `https://images.unsplash.com/${id}?w=600&auto=format&fit=crop&q=80`;

const artisan = (id, name, phone, craft, location, state, pehchanId, created, extra = {}) => ({
  id,
  name,
  phone,
  craft,
  location,
  state,
  pehchanId,
  kycVerified: true,
  status: "active",
  language: "hi",
  createdAt: created,
  ...extra,
});

const data = {
  artisans: [
    artisan(demoArtisanId, "Radha Devi", "9876543210", "pottery", "Khurja, Uttar Pradesh", "Uttar Pradesh", "PEHCHAN-UP-88213", daysAgo(160), {
      bio: "Third-generation potter from the Khurja ceramic cluster, known for hand-thrown vases and glazed tableware.",
    }),
    artisan(demoArtisan2Id, "Shanti Ram", "9812345678", "weaving", "Varanasi, Uttar Pradesh", "Uttar Pradesh", "PEHCHAN-UP-55104", daysAgo(140), {
      bio: "Handloom weaver from Varanasi carrying forward the Banarasi silk tradition.",
    }),
    artisan("artisan-demo-003", "Sita Devi", "9801122334", "painting", "Madhubani, Bihar", "Bihar", "PEHCHAN-BR-20417", daysAgo(120), {
      bio: "Madhubani painter using natural pigments and hand-made brushes, trained by her grandmother.",
    }),
    artisan("artisan-demo-004", "Ramesh Kumar", "9811223344", "woodwork", "Saharanpur, Uttar Pradesh", "Uttar Pradesh", "PEHCHAN-UP-61930", daysAgo(95)),
    artisan("artisan-demo-005", "Lalita Sharma", "9829012345", "weaving", "Barmer, Rajasthan", "Rajasthan", "PEHCHAN-RJ-44871", daysAgo(70), {
      language: "hi",
    }),
    artisan("artisan-demo-006", "Arjun Mehta", "9825098765", "woodwork", "Kutch, Gujarat", "Gujarat", "", daysAgo(12), {
      kycVerified: false,
      status: "pending",
      language: "gu",
    }),
    artisan("artisan-demo-007", "Kavita Kumari", "9832145678", "jewelry", "Jaipur, Rajasthan", "Rajasthan", "PEHCHAN-RJ-77310", daysAgo(45)),
    artisan("artisan-demo-008", "Bijay Nayak", "9437012345", "painting", "Raghurajpur, Odisha", "Odisha", "PEHCHAN-OD-10582", daysAgo(30), {
      language: "or",
    }),
    artisan("artisan-demo-009", "Farzana Begum", "9415098712", "embroidery", "Lucknow, Uttar Pradesh", "Uttar Pradesh", "", daysAgo(5), {
      kycVerified: false,
      status: "pending",
      language: "ur",
    }),
  ],
  buyers: [
    {
      id: demoBuyerId,
      name: "Rajiv Sharma",
      phone: "9123456780",
      companyName: "Rathi Exports Pvt Ltd",
      buyerType: "Exporter",
      city: "New Delhi",
      createdAt: daysAgo(150),
    },
    {
      id: "buyer-demo-002",
      name: "Ananya Gupta",
      phone: "9876500112",
      companyName: "Craft Bazaar Retail",
      buyerType: "Retailer",
      city: "Bengaluru",
      createdAt: daysAgo(90),
    },
  ],
  products: [
    {
      id: "d2ad72f4-61fc-4d62-b820-a2e1f15c3d03",
      artisanId: demoArtisanId,
      title: "Blue Pottery Vase — Jaipur Style",
      titleHi: "नीली मिट्टी का फूलदान",
      description:
        "Handmade blue pottery vase crafted in the traditional Jaipur style, using quartz clay and hand-painted floral motifs.",
      descriptionHi:
        "जयपुर की पारंपरिक ब्लू पॉटरी शैली में हाथ से बना फूलदान, क्वार्ट्ज मिट्टी और हाथ से चित्रित फूलों की कलाकृति के साथ।",
      craft: "pottery",
      category: "Home Decor",
      material: "Quartz clay, natural glaze",
      price: 650,
      priceMin: 550,
      priceMax: 815,
      imageUrl: img("photo-1578749556568-bc2c40e68b61"),
      views: 214,
      status: "published",
      createdAt: daysAgo(150),
    },
    {
      id: "ce7a456f-afae-4e5a-9f36-f048ccfebfe1",
      artisanId: demoArtisan2Id,
      title: "Hand-woven Banarasi Silk Dupatta",
      titleHi: "हाथ से बुना बनारसी दुपट्टा",
      description: "Authentic Varanasi handloom dupatta woven with fine silk threads and zari border.",
      descriptionHi: "प्राकृतिक रेशमी धागे और ज़री बॉर्डर से हाथ से बुना पारंपरिक बनारसी दुपट्टा।",
      craft: "weaving",
      category: "Textile",
      material: "Silk, zari thread",
      price: 1250,
      priceMin: 1060,
      priceMax: 1565,
      imageUrl: img("photo-1594040226829-7f251ab46d80"),
      views: 185,
      status: "published",
      createdAt: daysAgo(130),
    },
    {
      id: "fa318c42-871d-4054-9a84-7517c5b65109",
      artisanId: demoArtisanId,
      title: "Traditional Terracotta Water Pitcher",
      titleHi: "पारंपरिक मिट्टी का मटका",
      description: "Natural porous clay pitcher keeping water naturally cool, finished with ethnic etched lines.",
      descriptionHi: "प्राकृतिक मिट्टी से बना मटका जो पानी को ठंडा रखता है, पारंपरिक नक्काशी के साथ।",
      craft: "pottery",
      category: "Kitchen & Dining",
      material: "Terracotta clay",
      price: 450,
      priceMin: 385,
      priceMax: 565,
      imageUrl: img("photo-1493106641515-6b5631de4bb9"),
      views: 94,
      status: "published",
      createdAt: daysAgo(110),
    },
    {
      id: "97f0a714-3864-4a41-b844-325b3ea70e28",
      artisanId: demoArtisanId,
      title: "Madhubani Tree of Life Folk Art",
      titleHi: "मधुबनी ट्री ऑफ लाइफ पेंटिंग",
      description: "Handcrafted Madhubani wall art on handmade paper made with natural vegetable dyes.",
      descriptionHi: "प्राकृतिक रंगों से हस्तनिर्मित कागज़ पर बनी पारंपरिक मधुबनी पेंटिंग।",
      craft: "painting",
      category: "Wall Art",
      material: "Handmade paper, vegetable dyes",
      price: 1800,
      priceMin: 1530,
      priceMax: 2250,
      imageUrl: img("photo-1541961017774-22349e4a1262"),
      views: 310,
      status: "published",
      createdAt: daysAgo(100),
    },
    {
      id: "prod-demo-005",
      artisanId: "artisan-demo-003",
      title: "Handcrafted Madhubani Vase",
      titleHi: "हस्तनिर्मित मधुबनी फूलदान",
      description: "A handcrafted clay vase with traditional Madhubani art, made using natural colours.",
      descriptionHi: "यह एक हस्तनिर्मित मधुबनी कला से सजा मिट्टी का फूलदान है, जिसे प्राकृतिक रंगों से बनाया गया है।",
      craft: "painting",
      category: "Home Decor",
      material: "Clay, natural colours",
      price: 700,
      priceMin: 700,
      priceMax: 950,
      imageUrl: img("photo-1565193566173-7a0ee3dbe261"),
      views: 127,
      status: "published",
      createdAt: daysAgo(80),
    },
    {
      id: "prod-demo-006",
      artisanId: "artisan-demo-007",
      title: "Kundan Temple Necklace Set",
      titleHi: "कुंदन टेम्पल हार सेट",
      description: "Hand-set kundan necklace with matching earrings, inspired by South Indian temple jewellery.",
      descriptionHi: "हाथ से जड़ा कुंदन हार और झुमके, दक्षिण भारतीय मंदिर आभूषणों से प्रेरित।",
      craft: "jewelry",
      category: "Jewellery",
      material: "Brass, kundan stones, gold plating",
      price: 2400,
      priceMin: 2040,
      priceMax: 3000,
      imageUrl: img("photo-1601121141461-9d6647bca1ed"),
      views: 268,
      status: "published",
      createdAt: daysAgo(40),
    },
    {
      id: "prod-demo-007",
      artisanId: "artisan-demo-007",
      title: "Oxidised Silver Jhumka & Bangle Set",
      titleHi: "ऑक्सीडाइज़्ड चांदी झुमका सेट",
      description: "Tribal-style oxidised silver jewellery, hand-engraved by Jaipur silversmiths.",
      descriptionHi: "जयपुर के सुनारों द्वारा हाथ से नक्काशी किए गए ऑक्सीडाइज़्ड चांदी के आभूषण।",
      craft: "jewelry",
      category: "Jewellery",
      material: "Sterling silver",
      price: 1600,
      priceMin: 1360,
      priceMax: 2000,
      imageUrl: img("photo-1606760227091-3dd870d97f1d"),
      views: 141,
      status: "published",
      createdAt: daysAgo(35),
    },
    {
      id: "prod-demo-008",
      artisanId: "artisan-demo-004",
      title: "Sheesham Wood Side Table",
      titleHi: "शीशम लकड़ी की साइड टेबल",
      description: "Solid sheesham side table with a book shelf, hand-finished with natural oil polish.",
      descriptionHi: "किताबों की शेल्फ वाली शीशम की ठोस साइड टेबल, प्राकृतिक तेल से पॉलिश की गई।",
      craft: "woodwork",
      category: "Furniture",
      material: "Sheesham wood",
      price: 3200,
      priceMin: 2720,
      priceMax: 4000,
      imageUrl: img("photo-1611486212557-88be5ff6f941"),
      views: 76,
      status: "published",
      createdAt: daysAgo(60),
    },
    {
      id: "prod-demo-009",
      artisanId: "artisan-demo-005",
      title: "Handloom Cotton Cushion Covers (Set of 2)",
      titleHi: "हथकरघा सूती कुशन कवर (2 का सेट)",
      description: "Striped handloom cotton cushion covers woven on pit looms in Barmer.",
      descriptionHi: "बाड़मेर के गड्ढा करघों पर बुने धारीदार सूती कुशन कवर।",
      craft: "weaving",
      category: "Textile",
      material: "Handloom cotton",
      price: 850,
      priceMin: 720,
      priceMax: 1060,
      imageUrl: img("photo-1616627561950-9f746e330187"),
      views: 98,
      status: "published",
      createdAt: daysAgo(50),
    },
    {
      id: "prod-demo-010",
      artisanId: demoArtisanId,
      title: "Khurja Ceramic Cup Set",
      titleHi: "खुर्जा सिरेमिक कप सेट",
      description: "Set of four hand-thrown stoneware cups with a soft matte glaze.",
      descriptionHi: "मुलायम मैट ग्लेज़ वाले चार हाथ से बने स्टोनवेयर कप का सेट।",
      craft: "pottery",
      category: "Kitchen & Dining",
      material: "Stoneware clay",
      price: 520,
      priceMin: 440,
      priceMax: 650,
      imageUrl: img("photo-1590422749897-47036da0b0ff"),
      views: 63,
      status: "published",
      createdAt: daysAgo(20),
    },
    {
      id: "prod-demo-011",
      artisanId: "artisan-demo-008",
      title: "Pattachitra Wall Art Collection",
      titleHi: "पटचित्र वॉल आर्ट संग्रह",
      description: "Framed Pattachitra miniatures painted on treated cloth in Raghurajpur.",
      descriptionHi: "रघुराजपुर में उपचारित कपड़े पर बने फ्रेम किए गए पटचित्र।",
      craft: "painting",
      category: "Wall Art",
      material: "Cloth, natural pigments",
      price: 2100,
      priceMin: 1785,
      priceMax: 2625,
      imageUrl: img("photo-1513519245088-0e12902e5a38"),
      views: 88,
      status: "published",
      createdAt: daysAgo(25),
    },
    {
      id: "prod-demo-012",
      artisanId: "artisan-demo-006",
      title: "Kutch Carved Wooden Planter",
      titleHi: "कच्छ नक्काशीदार लकड़ी का गमला",
      description: "Hand-carved planter from Kutch, awaiting artisan verification.",
      descriptionHi: "कच्छ का हाथ से नक्काशीदार गमला।",
      craft: "woodwork",
      category: "Home Decor",
      material: "Mango wood",
      price: 900,
      priceMin: 765,
      priceMax: 1125,
      imageUrl: img("photo-1612196808214-b8e1d6145a8c"),
      views: 4,
      status: "pending",
      createdAt: daysAgo(8),
    },
  ],
  enquiries: [
    {
      id: "6dad62e9-ca37-4b5c-b069-274a4e532f26",
      productId: "d2ad72f4-61fc-4d62-b820-a2e1f15c3d03",
      artisanId: demoArtisanId,
      buyerId: demoBuyerId,
      buyerName: "Rajiv Sharma (Rathi Exports)",
      buyerType: "Exporter",
      buyerPhone: "9123456780",
      productTitle: "Blue Pottery Vase — Jaipur Style",
      quantity: 150,
      askingPrice: 650,
      budgetMin: 500,
      budgetMax: 560,
      requiredBy: daysAgo(-30).slice(0, 10),
      status: "negotiating",
      createdAt: daysAgo(0, 6),
      thread: [
        {
          id: uuid(),
          sender: "buyer",
          message: "Interested in bulk order for the European market. Can you do 150 pieces?",
          offerPrice: null,
          time: daysAgo(0, 6),
        },
        {
          id: uuid(),
          sender: "buyer",
          message: "For this bulk quantity of 150, can you offer ₹520 per piece?",
          offerPrice: 520,
          time: daysAgo(0, 5),
        },
      ],
    },
    {
      id: "b5f6a954-479c-4968-9105-0553d53df42f",
      productId: "ce7a456f-afae-4e5a-9f36-f048ccfebfe1",
      artisanId: demoArtisan2Id,
      buyerId: "buyer-demo-002",
      buyerName: "Ananya Gupta (Craft Bazaar)",
      buyerType: "Retailer",
      buyerPhone: "9876500112",
      productTitle: "Hand-woven Banarasi Silk Dupatta",
      quantity: 40,
      askingPrice: 1250,
      status: "open",
      createdAt: daysAgo(1),
      thread: [
        {
          id: uuid(),
          sender: "buyer",
          message: "We stock handloom textiles across 12 stores. Can you supply 40/month?",
          offerPrice: null,
          time: daysAgo(1),
        },
      ],
    },
    {
      id: "enq-demo-003",
      productId: "fa318c42-871d-4054-9a84-7517c5b65109",
      artisanId: demoArtisanId,
      buyerId: demoBuyerId,
      buyerName: "Rajiv Sharma (Rathi Exports)",
      buyerType: "Exporter",
      buyerPhone: "9123456780",
      productTitle: "Traditional Terracotta Water Pitcher",
      quantity: 60,
      askingPrice: 450,
      status: "deal_closed",
      finalPrice: 425,
      totalAmount: 25500,
      createdAt: daysAgo(15),
      thread: [
        {
          id: uuid(),
          sender: "buyer",
          message: "We need 60 pitchers for a summer promotion. ₹400 per piece?",
          offerPrice: 400,
          time: daysAgo(15),
        },
        {
          id: uuid(),
          sender: "artisan",
          message: "Countered at ₹425/piece.",
          offerPrice: 425,
          time: daysAgo(14, 20),
        },
        {
          id: uuid(),
          sender: "buyer",
          message: "🤝 Deal Confirmed! Agreed at ₹425/piece for 60 items (Total: ₹25500). Payment: Escrow / Cash on Delivery.",
          offerPrice: 425,
          time: daysAgo(14, 18),
        },
      ],
    },
  ],
  settings: {
    announcement: "PM Vishwakarma registrations are open — verify your Pehchan ID to get the verified badge.",
    categories: ["Pottery", "Weaving", "Painting", "Jewelry", "Woodwork", "Embroidery"],
  },
};

save(data);
console.log("Seeded data.json with demo artisans, buyers, products and enquiries.");
