const { v4: uuid } = require("uuid");
const { save } = require("./db");

const demoArtisanId = "artisan-demo-001";
const demoArtisan2Id = "artisan-demo-002";
const demoBuyerId = "buyer-demo-001";

const data = {
  artisans: [
    {
      id: demoArtisanId,
      name: "Radha Devi",
      phone: "9876543210",
      craft: "pottery",
      location: "Khurja, Uttar Pradesh",
      pehchanId: "PEHCHAN-UP-88213",
      kycVerified: true,
      language: "hi",
      createdAt: new Date().toISOString(),
    },
    {
      id: demoArtisan2Id,
      name: "Shanti Ram",
      phone: "9812345678",
      craft: "weaving",
      location: "Varanasi, Uttar Pradesh",
      pehchanId: "PEHCHAN-UP-55104",
      kycVerified: true,
      language: "hi",
      createdAt: new Date().toISOString(),
    },
  ],
  buyers: [
    {
      id: demoBuyerId,
      name: "Rajiv Sharma",
      phone: "9123456780",
      companyName: "Rathi Exports Pvt Ltd",
      buyerType: "Exporter",
      city: "New Delhi",
      createdAt: new Date().toISOString(),
    },
    {
      id: "buyer-demo-002",
      name: "Ananya Gupta",
      phone: "9876500112",
      companyName: "Craft Bazaar Retail",
      buyerType: "Retailer",
      city: "Bengaluru",
      createdAt: new Date().toISOString(),
    },
  ],
  products: [
    {
      id: "d2ad72f4-61fc-4d62-b820-a2e1f15c3d03",
      artisanId: demoArtisanId,
      title: "Blue Pottery Vase — Jaipur Style",
      titleHi: "नीली मिट्टी का फूलदान",
      description:
        "Handmade blue pottery vase crafted in the traditional Jaipur style, using quartz clay and hand-painted floral motifs.",
      descriptionHi:
        "जयपुर की पारंपरिक ब्लू पॉटरी शैली में हाथ से बना फूलदान, क्वार्ट्ज मिट्टी और हाथ से चित्रित फूलों की कलाकृति के साथ।",
      craft: "pottery",
      category: "Home Decor",
      price: 650,
      imageUrl: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=600&auto=format&fit=crop&q=80",
      views: 214,
      status: "published",
      createdAt: new Date().toISOString(),
    },
    {
      id: "ce7a456f-afae-4e5a-9f36-f048ccfebfe1",
      artisanId: demoArtisan2Id,
      title: "Hand-woven Banarasi Silk Dupatta",
      titleHi: "हाथ से बुना बनारसी दुपट्टा",
      description: "Authentic Varanasi handloom dupatta woven with fine silk threads and zari border.",
      descriptionHi: "प्राकृतिक रेशमी धागे और ज़री बॉर्डर से हाथ से बुना पारंपरिक बनारसी दुपट्टा।",
      craft: "weaving",
      category: "Textile",
      price: 1250,
      imageUrl: "https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?w=600&auto=format&fit=crop&q=80",
      views: 185,
      status: "published",
      createdAt: new Date().toISOString(),
    },
    {
      id: "fa318c42-871d-4054-9a84-7517c5b65109",
      artisanId: demoArtisanId,
      title: "Traditional Terracotta Water Pitcher",
      titleHi: "पारंपरिक मिट्टी का मटका",
      description: "Natural porous clay pitcher keeping water naturally cool, finished with ethnic etched lines.",
      descriptionHi: "प्राकृतिक मिट्टी से बना मटका जो पानी को ठंडा रखता है, पारंपरिक नक्काशी के साथ।",
      craft: "pottery",
      category: "Kitchen & Dining",
      price: 450,
      imageUrl: "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=600&auto=format&fit=crop&q=80",
      views: 94,
      status: "published",
      createdAt: new Date().toISOString(),
    },
    {
      id: "97f0a714-3864-4a41-b844-325b3ea70e28",
      artisanId: demoArtisanId,
      title: "Madhubani Tree of Life Folk Art",
      titleHi: "मधुबनी ट्री ऑफ लाइफ पेंटिंग",
      description: "Handcrafted Madhubani wall art on handmade paper made with natural vegetable dyes.",
      descriptionHi: "प्राकृतिक रंगों से हस्तनिर्मित कागज़ पर बनी पारंपरिक मधुबनी पेंटिंग।",
      craft: "painting",
      category: "Wall Art",
      price: 1800,
      imageUrl: "https://images.unsplash.com/photo-1582561424760-0321d75e81fa?w=600&auto=format&fit=crop&q=80",
      views: 310,
      status: "published",
      createdAt: new Date().toISOString(),
    },
  ],
  enquiries: [
    {
      id: "6dad62e9-ca37-4b5c-b069-274a4e532f26",
      productId: "d2ad72f4-61fc-4d62-b820-a2e1f15c3d03",
      artisanId: demoArtisanId,
      buyerId: demoBuyerId,
      buyerName: "Rajiv Sharma (Rathi Exports)",
      buyerType: "Exporter",
      buyerPhone: "9123456780",
      productTitle: "Blue Pottery Vase — Jaipur Style",
      quantity: 150,
      askingPrice: 650,
      status: "negotiating",
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
      thread: [
        {
          id: uuid(),
          sender: "buyer",
          message: "Interested in bulk order for the European market. Can you do 150 pieces?",
          offerPrice: null,
          time: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
        },
        {
          id: uuid(),
          sender: "buyer",
          message: "For this bulk quantity of 150, can you offer ₹520 per piece?",
          offerPrice: 520,
          time: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
        },
      ],
    },
    {
      id: "b5f6a954-479c-4968-9105-0553d53df42f",
      productId: "ce7a456f-afae-4e5a-9f36-f048ccfebfe1",
      artisanId: demoArtisan2Id,
      buyerId: "buyer-demo-002",
      buyerName: "Ananya Gupta (Craft Bazaar)",
      buyerType: "Retailer",
      buyerPhone: "9876500112",
      productTitle: "Hand-woven Banarasi Silk Dupatta",
      quantity: 40,
      askingPrice: 1250,
      status: "open",
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
      thread: [
        {
          id: uuid(),
          sender: "buyer",
          message: "We stock handloom textiles across 12 stores. Can you supply 40/month?",
          offerPrice: null,
          time: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
        },
      ],
    },
  ],
};

save(data);
console.log("Seeded data.json with demo artisans, buyers, products and enquiries.");
